services:
  - type: web
    name: http-lab-api
    runtime: docker
    plan: free
    rootDir: crud-api
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/products
    autoDeployTrigger: commit

  - type: web
    name: http-lab
    runtime: docker
    plan: free
    rootDir: crud-frontend-axios
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: BACKEND_SCHEME
        value: https
      - key: BACKEND_HOST
        fromService:
          type: web
          name: http-lab-api
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: BACKEND_PORT
        value: "443"
